# Generated by Django 3.1 on 2021-01-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4)),
                ('open', models.FloatField(null=True)),
                ('fifty_two_lo', models.FloatField(null=True)),
                ('fifty_two_hi', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('avg_volume', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
                ('pe_ratio', models.FloatField(null=True)),
                ('eps_ratio', models.FloatField(null=True)),
            ],
        ),
    ]
